### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/timeout-as-a-service#10]
If someone submitted a pull request that broke this internet-critical service and we had no tests to block it, the world might stop rotating on its axis. We can't have that... :no_good_man: 

In all likelihood, the culprit will be me...

# Tests
 1. {`GET`, `PUT`, `POST`, `DELETE`} requests, with
 1. {`3000`, `10000`} millisecond wait times, and
 1. {`200`, `418`} return codes
 1. Test the malformed request `/`
 1. Test the malformed request `/abc/123`

**Comment by ericadamski** [comment]
@michaelsanford I can give this a go, my first time contributing to OSS 😄

**Comment by michaelsanford** [comment]
Welcome @ericadamski; it's yours! 👍 

If you have any more questions, do come back and discuss.

**Comment by pradeephbac** [comment]
Hi, I just started in this Node API project by creating Heroku Deploy Button and like to contribute on test cases.

**Comment by ericadamski** [comment]
@pradeephbac I have already completed the test, opening a PR now

**Comment by ericadamski** [comment]
@pradeephbac you are welcome to review the PR when its up

**Comment by pradeephbac** [comment]
Sure. Awesome :)

**Comment by ericadamski** [comment]
PR is here @pradeephbac https://github.com/michaelsanford/timeout-as-a-service/pull/23
