### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/timeout-as-a-service#17]

**Comment by hellotunmbi** [comment]
I'll like to work on this. I see you assigned it to yourself. Can I do it or just leave it for you to fix?

**Comment by michaelsanford** [comment]
Hi @hellotunmbi ! It's to enable PRs as part of the event (since I don't currently have one).

Do check back and take any of the other issues I tag :)

**Comment by michaelsanford** [comment]
I'll make this simpler. Please check back for other issues, which I'll create and tag now.

Thanks!

**Comment by michaelsanford** [comment]
Hi again @hellotunmbi !

Would you like to work on some documentation in a Github Pages-style site for this repo (#6) ? It's very simple, you can mostly take what's in the readme and make it look nicer.
