### ISSUE TITLE
Create a 'Deploy to Heroku' Button

### ISSUE THREAD

**Issue by michaelsanford** [michaelsanford/timeout-as-a-service#20]
Create a 'Deploy to Heroku' Button for this project.

https://devcenter.heroku.com/articles/heroku-button

Most of the "value" in this somewhat toy project is the ability to use it quasi-internally for your own projects. Since I already deploy it to Heroku, might as well try this!

It's open for anyone to contribute to, but it would be really handy _if you actually have a Heroku account to test it with_ 😉

**Comment by pradeephbac** [comment]
Hi, I would like to contribute for this issue. And I Added Deploy To Heroku button on landing page.We can also add Heroku button on readme.md file also.
